var translations = {
    market_B : "Исход матча",
    market_O : "Фора",
    market_T : "Тотал",
    bcg_Basic : "Исход матча",
    bcg_Total : "Тотал",
    bcg_Team1_Total : "Инд. тотал 1К",
    bcg_Team2_Total : "Инд. тотал 2К",
    bcg_Odds : "Фора",
    bcg_Team12_Goal : "Забьют обе?",
    bcg_Total_EO : "Тотал матча",
    bc_T_Even : "четный",
    bc_T_Odd : "нечетный",
    bc_T_V : "Тотал",
    bc_T_L : "Больше",
    bc_T_G : "Меньше",
    bc_HT_T_V : "Тотал",
    bc_HT_T_L : "Больше",
    bc_HT_T_G : "Меньше",

    bc_HT_1O : "Ф1",
    bc_HT_1O_V : "КФ1",
    bc_HT_2O : "Ф2",
    bc_HT_2O_V : "КФ2",

    bc_T_01 : "0-1 гола",
    bc_T_23 : "2-3 гола",
    bc_T_4P : "4 и больше голов",
    bcg_NHL : "С овертаймом и буллитами",
    bc_1OT : "победа 1К в овертайме",
    bc_XOT : "ничья в овертайме",
    bc_2OT : "победа 2К в овертайме",
    bc_1P : "победа 1К по буллитам",
    bc_2P : "победа 2К по буллитам",
    bcg_HalfFullTime : "Тайм/Матч",
    bc_hf11 : "П1П1",
    bc_hf1X : "П1Н",
    bc_hf12 : "П1П2",
    bc_hfX1 : "НП1",
    bc_hfXX : "НН",
    bc_hfX2 : "НП2",
    bc_hf21 : "П2П1",
    bc_hf2X : "П2Н",
    bc_hf22 : "П2П2",
    bc_HT_1 : "П1",
    bc_HT_X : "Х",
    bc_HT_2 : "П2",
    bcg_Team12_Goal : "Забют обе?",
    bc_T12_Goal_Y : "Обе забьют",
    bc_T12_Goal_N : "Хотя бы одна не забьет",
    bcg_P12_T1_Goal_YN : "Забьет 1К в каждом тайме?",
    bcg_P12_T2_Goal_YN : "Забьет 2К в каждом тайме?",
    bcg_AwayOff : "удаление игрока с поля",
    bcg_Pass : "Проход",
    bc_Pass_1 : "Проход 1К",
    bc_Pass_X : "Никто не пройдет",
    bc_Pass_2 : "Проход 2К",
    bcg_Next_Goal : "Кто забьет следующий гол?",
    bc_P12_T1_Goal_Y : "Да",
    bc_P12_T1_Goal_N : "Нет",
    bc_P12_T2_Goal_Y : "Да",
    bc_P12_T2_Goal_N : "Нет",
    bc_G1_1 : "1 гол забъет 1К",
    bc_G2_1 : "2 гол забъет 1К",
    bc_G3_1 : "3 гол забъет 1К",
    bc_G4_1 : "4 гол забъет 1К",
    bc_G5_1 : "5 гол забъет 1К",
    bc_G6_1 : "6 гол забъет 1К",
    bc_G7_1 : "7 гол забъет 1К",
    bc_G8_1 : "8 гол забъет 1К",
    bc_G9_1 : "9 гол забъет 1К",
    bc_G1_2 : "1 гол забъет 2К",
    bc_G2_2 : "2 гол забъет 2К",
    bc_G3_2 : "3 гол забъет 2К",
    bc_G4_2 : "4 гол забъет 2К",
    bc_G5_2 : "5 гол забъет 2К",
    bc_G6_2 : "6 гол забъет 2К",
    bc_G7_2 : "7 гол забъет 2К",
    bc_G8_2 : "8 гол забъет 2К",
    bc_G9_2 : "9 гол забъет 2К",
    bc_G1_X : "1 голa не будет",
    bc_G2_X : "2 голa не будет",
    bc_G3_X : "3 голa не будет",
    bc_G4_X : "4 голa не будет",
    bc_G5_X : "5 голa не будет",
    bc_G6_X : "6 голa не будет",
    bc_G7_X : "7 голa не будет",
    bc_G8_X : "8 голa не будет",
    bc_G9_X : "9 голa не будет",
    bc_ss00 : "0:0",
    bc_ss01 : "0:1",
    bc_ss02 : "0:2",
    bc_ss03 : "0:3",
    bc_ss10 : "1:0",
    bc_ss11 : "1:1",
    bc_ss12 : "1:2",
    bc_ss13 : "1:3",
    bc_ss20 : "2:0",
    bc_ss21 : "2:1",
    bc_ss22 : "2:2",
    bc_ss23 : "2:3",
    bc_ss30 : "3:0",
    bc_ss31 : "3:1",
    bc_ss32 : "3:2",
    bc_ss33 : "3:3",
    bc_cs00 : "0:0",
    bc_cs01 : "0:1",
    bc_cs02 : "0:2",
    bc_cs03 : "0:3",
    bc_cs10 : "1:0",
    bc_cs11 : "1:1",
    bc_cs12 : "1:2",
    bc_cs13 : "1:3",
    bc_cs20 : "2:0",
    bc_cs21 : "2:1",
    bc_cs22 : "2:2",
    bc_cs23 : "2:3",
    bc_cs30 : "3:0",
    bc_cs31 : "3:1",
    bc_cs32 : "3:2",
    bc_cs33 : "3:3",
    bcg_SeriesScore1 : "Счет 1 периода",
    bcg_SeriesScore2 : "Счет 2 периода",
    bcg_SeriesScore3 : "Счет 3 периода",
    bcg_SeriesScore4 : "Счет 4 периода",
    bcg_P1_T1_Goal : "Забьет 1К в первом тайме?",
    bcg_P2_T1_Goal : "Забьет 1К во втором тайме?",
    bcg_P1_T2_Goal : "Забьет 2К в первом тайме?",
    bcg_P2_T2_Goal : "Забьет 2К во втором тайме?",
    bcg_P1_T12_Goal_YN : "Будет гол в первом тайме?",
    bc_P1_T12_Goal_Y : "Да",
    bc_P1_T12_Goal_N : "Нет",
    bcg_P1_T12_Goal_YN : "Будет гол во втором тайме?",
    bc_P2_T12_Goal_Y : "Да",
    bc_P2_T12_Goal_N : "Нет",
    bc_P1_T1_Goal_Y : "Да",
    bc_P2_T1_Goal_Y : "Да",
    bc_P1_T1_Goal_N : "Нет",
    bc_P2_T1_Goal_N : "Нет",
    bc_P1_T2_Goal_Y : "Да",
    bc_P2_T2_Goal_Y : "Да",
    bc_P1_T2_Goal_N : "Нет",
    bc_P2_T2_Goal_N : "Нет",
    bcg_Unknown : "Неизвестно",
    status_OT : "Овертайм",
    status_Pen : "Пенальти",
    status_Abd : "Матч прекращен",
    status_Int : "Матч прерван",
    status_Off : "Матч перенесен",
    status_Can : "Матч отменен",
    liveStatus_2 : "Прием ставок приостановлен",
    liveStatus_3 : "Прием ставок в перерыве",
    liveStatus_4 : "Прием ставок в перерыве приостановлен"
};
var periods_names = {
    skind_2 : "-я четверть",
    skind_8 : "-й сет",
    skind_9 : "-й тайм",
    skind_18 : "-й сет",
    skind_21 : "-й тайм",
    skind_23 : "-й период",
    skind_29 : "-й сет"
};
//Количество периодов по видам спорта
var periods_table = {
    skind_2 : "4",
    skind_8 : "3",
    skind_9 : "3",
    skind_18 : "tenis",
    skind_21 : "2",
    skind_22 : "3",
    skind_23 : "3",
    skind_30 : "3"
};
//Подгружаем тамлайны
var templates = {
    tplBar_2 : "events_bar_2.html",
    tplBar_9 : "events_bar_9.html",
    tplBar_21 : "events_bar_21.html",
    tplBar_22 : "events_bar_22.html",
    tplBar_23 : "events_bar_23.html",
    tplBar_30 : "events_bar_30.html"
};